<?php

namespace AppBundle\Repository;

/**
 * PostImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostImageRepository extends \Doctrine\ORM\EntityRepository
{
}
